### ISSUE TITLE
文件无法拉取

### ISSUE THREAD

**Issue by Schog** [loveincode/notes#5]
/06-DB数据/Mysql/MySQL十大经典错误案例.md
文件名中存在特殊字符，导致无法clone

**Comment by loveincode** [comment]
哪里提示的存在特殊字符？我这边clone没有问题。
![Jietu20190513-192400](https://user-images.githubusercontent.com/29159573/57618017-df27c780-75b4-11e9-882e-1f16f0f233c5.jpg)

**Comment by Schog** [comment]
MySQL十大经典错误案例.md
文件名，我这边拉取的时候，案例后面存在一个特殊字符，win10系统下无法通过小乌龟拉取至本地

**Comment by loveincode** [comment]
![image](https://user-images.githubusercontent.com/29159573/57666760-ad097a80-7633-11e9-842c-73717db3c2e5.png)
正常的吧，windows 推荐你下载一个git客户端 https://gitforwindows.org/。
